/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Cadinho;
import static java.lang.String.valueOf;
import java.math.BigDecimal;

/**
 *
 * @author Rodnei
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPesoA = new javax.swing.JFormattedTextField();
        txtPesoB = new javax.swing.JFormattedTextField();
        txtPesoC = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        txtResultado = new javax.swing.JLabel();
        txtContador = new javax.swing.JButton();
        lblContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("Análises de Umidade V1.0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 570, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cbc.jpg"))); // NOI18N
        jLabel2.setAutoscrolls(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 190, 120));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Desenvolvido por RODNEI MIRANDA DA SILVA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Cadinho zerado A");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Cadinho com +- 10g amostra B");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Cadinho após 2 horas C");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Tempo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Resultado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Adicionar H2O:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        txtPesoA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###,####"))));
        txtPesoA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPesoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoAActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, -1));

        txtPesoB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###,####"))));
        txtPesoB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPesoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoBActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, -1));

        txtPesoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###,####"))));
        txtPesoC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPesoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoCActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 210, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Calcular Umidade");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 180, 60));

        txtResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 180, 40));

        txtContador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContador.setText("Iniciar Secagem");
        txtContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 60));

        lblContador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(lblContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 120, 30));

        setBounds(0, 0, 816, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoAActionPerformed

    private void txtPesoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoBActionPerformed

    private void txtPesoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    Cadinho cad = new Cadinho();
    BigDecimal PesA = new BigDecimal(valueOf(txtPesoA.getText()));
    BigDecimal PesB = new BigDecimal(valueOf(txtPesoB.getText()));
    cad.setPesoA(PesA);
    cad.setPesoB(PesB);
    cad.CalcularUmidade(PesA, PesB, PesB);
    txtResultado.setText(valueOf(cad.getResultado()));
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblContador;
    private javax.swing.JButton txtContador;
    private javax.swing.JFormattedTextField txtPesoA;
    private javax.swing.JFormattedTextField txtPesoB;
    private javax.swing.JFormattedTextField txtPesoC;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
